import {Dimensions, StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  centeredView: {
    backgroundColor: 'rgba(52, 52, 52, 0.7)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    height: '35%',
    position: 'relative',
    alignItems: 'center',
  },
  modalView: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    borderRadius: 15,
    paddingHorizontal: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'relative',
  },
  button: {
    width: '100%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a1705a',
    borderRadius: 25,
    padding: 10,
    elevation: 2,
    marginBottom: 20,
    marginTop: 30,
  },
  button2: {
    width: '100%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f3f3',
    borderRadius: 25,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#00BA00',
  },
  buttonClose: {
    backgroundColor: '#00BA00',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
  },
  textStyle2: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
  },
  modalText: {
    color: '#333',
    fontWeight: '500',
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 20,
    marginTop: 25,
  },
  modalText2: {
    color: '#333',
    fontWeight: '400',
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 5,
  },
});
