import {Dimensions, StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  centeredView: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: 'white',
    width: '100%',
    height: '100%',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    width: '90%',
    height: '80%',
    backgroundColor: 'white',
    paddingTop: 20,
    paddingBottom: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'relative',
  },
  modalText: {
    color: '#a1705a',
    fontSize: 22,
    fontWeight: '400',
    letterSpacing: 0.5,
    paddingBottom: 5,
  },
  image: {
    width: 130,
    height: 130,
  },
  paymentDetailsContainer: {
    width: '100%',
    marginTop: 40,
    paddingHorizontal: 20,
  },
  paymentDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  paymentDetailsText: {
    color: '#666',
  },
  paymentDetailsText2: {
    color: 'black',
    fontSize: 16,
    fontWeight: '500',
  },
  buttonContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 30,
  },
  button: {
    width: '39%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a1705a',
    borderRadius: 25,
    padding: 10,
    elevation: 2,
    marginLeft: 10,
  },
  button2: {
    width: '39%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f3f3',
    borderRadius: 25,
    padding: 10,
    elevation: 2,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
  },
  textStyle2: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
  },
});
