import {Dimensions, StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  centeredView: {
    backgroundColor: 'white',
    // flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: 'white',
    width: '100%',
    height: '100%',
    position: 'relative',
    alignItems: 'center',
  },
  modalHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 20,
    borderBottomWidth: 10,
    borderBottomColor: '#f3f3f3',
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  modalHeading: {
    color: '#000',
    fontSize: 18,
    fontWeight: '500',
  },
  buttonContainer: {
    backgroundColor: 'white',
    paddingHorizontal: 10,
    paddingVertical: 20,
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  button: {
    width: '100%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a1705a',
    borderRadius: 5,
    padding: 10,
    elevation: 2,
    marginBottom: 20,
    marginTop: 30,
  },
  form: {
    width: "100%",
    paddingHorizontal: 15,
    paddingBottom: 15,
    borderBottomColor: '#ccc',
    borderBottomWidth: 0.7,
  },
  inputContainer: {
    width: '100%',
    borderColor: '#ccc',
    borderWidth: 0.7,
    borderRadius: 10,
    color: '#000',
    paddingTop: 3,
    marginBottom: 10,
  },
  inputContainerLabel: {
    fontSize: 12,
    fontWeight: '400',
    color: '#666',
    paddingHorizontal: 10,
    position: 'absolute',
    top: 5,
  },
  inputContainerInput: {
    height: 40,
    color: 'black',
    paddingHorizontal: 10,
    marginTop: 8,
  },
  info: {
    fontSize: 14,
    fontWeight: '400',
    color: '#666',
    marginBottom: 15,
  },
  resend: {
    fontSize: 14,
    fontWeight: '400',
    color: '#a1705a',
  },
});
