import {Dimensions, StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  centeredView: {
    backgroundColor: 'rgba(52, 52, 52, 0.7)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    height: '43%',
    position: 'relative',
    alignItems: 'center',
  },
  modalView: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'relative',
  },
  modalHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderBottomWidth: 10,
    borderBottomColor: '#f3f3f3',
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  modalHeading: {
    color: '#000',
    fontSize: 18,
    fontWeight: '500',
  },
  buttonContainer: {
    width: "100%",
    paddingHorizontal: 15,
  },
  button: {
    width: '100%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#a1705a',
    borderRadius: 5,
    padding: 10,
    elevation: 2,
    marginBottom: 20,
    marginTop: 30,
  },
  form: {
    paddingHorizontal: 15,
  },
  inputContainer: {
    width: '100%',
    height: 150,
    borderWidth: 0,
    borderColor: '#ccc',
    borderWidth: 0.7,
    borderRadius: 10,
    color: '#000',
    paddingTop: 3,
    paddingBottom: 5,
    marginBottom: 15,
  },
  inputContainerLabel: {
    fontSize: 12,
    fontWeight: '400',
    color: '#666',
    paddingHorizontal: 10,
    position: 'absolute',
    top: 5,
  },
  inputContainerInput: {
    flex: 1,
    color: 'black',
    paddingHorizontal: 10,
    marginTop: 15,
    textAlignVertical: 'top',
  },
});
