import {Dimensions, StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  // Modal
  centeredView: {
    backgroundColor: 'rgba(52, 52, 52, 0.7)',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    height: '67%',
    position: 'relative',
    alignItems: 'center',
  },
  modalView: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    paddingTop: 20,
    paddingBottom: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    position: 'relative',
  },
  modalHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderBottomWidth: 10,
    borderBottomColor: '#f3f3f3',
    paddingHorizontal: 20,
    paddingBottom: 15,
  },
  modalHeading: {
    color: '#000',
    fontSize: 18,
    fontWeight: '500',
  },
  modalButtonContainer: {
    width: '100%',
    backgroundColor: 'white',
    paddingHorizontal: 20,
    position: 'absolute',
    bottom: 0,
  },
  modalButton: {
    width: '100%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00BA00',
    borderRadius: 5,
    padding: 10,
    elevation: 2,
    position: 'absolute',
    bottom: 35,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  modalButtonDisabled: {
    width: '100%',
    height: 40,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    elevation: 2,
    position: 'absolute',
    bottom: 35,
  },
});
