import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  loginContainer: {
    height: '100%',
    backgroundColor: 'white',
    position: 'relative',
  },
  backgroundImageContainer: {
    position: 'relative',
  },
  backgroundImage: {
    height: '100%',
    resizeMode: 'cover',
  },
  loginFormContainer: {
    backgroundColor: 'rgba(52, 52, 52, 0.6)',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
  },
  loginFormLogoContainer: {
    height: '35%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    height: 130,
    resizeMode: 'contain',
  },
  loginFormHeading: {
    color: 'white',
    fontSize: 25,
    fontWeight: '700',
    letterSpacing: 0.5,
    paddingBottom: 5,
  },
  loginForm: {
    backgroundColor: '#fff',
    width: '100%',
    height: '65%',
    padding: 30,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    position: 'absolute',
    bottom: 0,
    flexDirection: 'column',
    alignItems: 'center',
  },
  loginContainerForm: {
    width: '100%',
    marginTop: '10%',
  },
  loginFormHeadingContainer: {
    width: '100%',
  },
  loginFormHeading2: {
    color: 'rgb(92, 64, 51)',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
  },
  loginFormInputContainer: {
    flexDirection: 'column',
    marginBottom: 30,
  },
  loginFormLabel: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
  },
  loginFormInput: {
    width: '100%',
    height: 40,
    borderWidth: 0,
    borderBottomColor: 'rgb(92, 64, 51)',
    borderBottomWidth: 0.7,
    color: '#000',
  },
  loginContainerButtons: {
    width: '100%',
    marginTop: '3%',
  },
  loginLink: {width: 'auto', flexDirection: 'row', justifyContent: 'center'},
  loginLinkText: {
    color: 'rgb(92, 64, 51)',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
    textAlign: 'center',
    marginBottom: 5,
  },
  loginLinkText2: {
    color: '#666',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
    textAlign: 'center',
    marginBottom: 5,
    marginLeft: 5,
  },
  loginButtonContainer: {
    width: '100%',
    position: 'relative',
    top: 50,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  loginButton: {
    width: '100%',
    height: 45,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(92, 64, 51)',
    borderRadius: 30,
  },
  loginButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
});
