import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  loginContainer: {
    height: '100%',
    backgroundColor: 'white',
    position: 'relative',
  },
  backgroundImageContainer: {
    position: 'relative',
  },
  backgroundImage: {
    height: '100%',
    resizeMode: 'cover',
  },
  loginFormContainer: {
    backgroundColor: 'rgba(52, 52, 52, 0.6)',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginForm: {
    backgroundColor: '#fff',
    width: '85%',
    height: '75%',
    paddingVertical: 30,
    paddingHorizontal: 20,
    borderRadius: 30,
    borderRadius: 30,
    flexDirection: 'column',
    alignItems: 'center',
  },
  loginContainerForm: {
    width: '100%',
    marginTop: '10%',
  },
  loginFormHeadingContainer: {
    width: '100%',
  },
  loginFormHeading2: {
    color: 'rgb(92, 64, 51)',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
  },
  prompt: {
    color: '#000',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.5,
    paddingBottom: 5,
  },
  loginFormInputContainer: {
    flexDirection: 'column',
    marginBottom: 30,
  },
  loginFormLabel: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
  },
  loginFormInput: {
    backgroundColor: 'rgb(0, 0, 0, 0, 0.1)',
    width: '100%',
    height: 48,
    borderWidth: 0,
    borderColor: '#ccc',
    borderWidth: 0.7,
    borderRadius: 10,
    color: '#000',
    paddingLeft: 5,
  },
  loginContainerButtons: {
    width: '100%',
    marginTop: '3%',
    position: 'absolute',
    bottom: 20,
  },
  loginLink: {width: 'auto', flexDirection: 'row', justifyContent: 'center'},
  loginLinkText: {
    color: 'rgb(92, 64, 51)',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
    textAlign: 'center',
    marginBottom: 5,
  },
  loginLinkText2: {
    color: '#666',
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
    paddingBottom: 5,
    textAlign: 'center',
    marginBottom: 5,
    marginLeft: 5,
  },
  loginButtonContainer: {
    width: '100%',
    position: 'absolute',
    bottom: 30,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  loginButton: {
    width: '100%',
    height: 45,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(92, 64, 51)',
    borderRadius: 30,
  },
  loginButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
});
