import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    width: '100%',
    height: '100%',
  },
  homeHeader: {
    backgroundColor: '#fff',
    width: '100%',
    paddingVertical: 20,
    paddingHorizontal: 15,
    paddingTop: '14%',
  },
  navbar: {
    backgroundColor: '#900',
    position: 'relative',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  profile__pic: {
    width: 40,
    height: 40,
    borderRadius: 100,
    marginTop: -5,
    shadowColor: '#52006A',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  homeSearchContainer: {
    backgroundColor: '#fff',
    width: '100%',
    height: 45,
    borderRadius: 5,
    borderWidth: 0,
    color: '#000',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    borderColor: '#ccc',
    borderWidth: 0.7,
  },
  homeSearchInput: {
    flex: 1,
  },
  advertContainer: {
    paddingHorizontal: 15,
    height: 190,
  },
  imageSlider: {},
  sliderImage: {
    width: '100%',
    height: 150,
    marginRight: 20,
  },
  paginationStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: 10,
    marginBottom: 10,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    margin: 3,
    backgroundColor: '#ccc',
  },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    margin: 3,
    backgroundColor: '#333',
  },
  body: {},
  heading: {
    color: 'black',
    fontSize: 18,
    fontWeight: '500',
    marginLeft: 15,
    marginVertical: 10,
  },
  dishContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    paddingHorizontal: 15,
  },
});
